/*
    Given an integer n, return the number of trailing zeroes in n!.

        Note: Your solution should be in logarithmic time complexity.
*/

/*
    Zero can only be generated by 5 * 2. As there are many more 2s than
        5, we only have to count the number of 5s.
*/
class Solution 
{
public:
    int trailingZeroes(int n) 
    {
        int q = n/5;
        int cnt = 0;
        while(q > 0)
        {
            cnt += q;
            q /= 5;
        }
        return cnt;
    }
};